'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace WindowsFormsApplication1

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class PrintRibbonControllerResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(WindowsFormsApplication1.PrintRibbonControllerResources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsFormsApplication1.PrintRibbonControllerResources", GetType(WindowsFormsApplication1.PrintRibbonControllerResources).Assembly)
                    WindowsFormsApplication1.PrintRibbonControllerResources.resourceMan = temp
                End If

                Return WindowsFormsApplication1.PrintRibbonControllerResources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Customize As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Customize", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Document As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Document", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFile", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMht", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXls", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackground", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Find As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Find", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FindLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_HandTool As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_HandTool", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Magnifier", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Open As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Open", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMargins", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3 As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4 As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5 As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6 As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSize", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Parameters As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Parameters", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Pointer As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Pointer", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Print As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Print", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Save As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Save", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Scale As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Scale", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsv", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFile", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMht", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdf", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtf", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxt", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXls", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Watermark As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Watermark", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Zoom As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Zoom", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = WindowsFormsApplication1.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", WindowsFormsApplication1.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
